config/routes.rb
Rails.application.routes.draw do

  # get 'static_pages/login'
  # get 'static_pages/home'
  # get 'static_pages/help'
  # get 'static_pages/about'

  get  '/help',    to: 'static_pages#help'
  get  '/about',    to: 'static_pages#about'
  get  '/home',    to: 'static_pages#home'
  get  '/login',  to: 'static_pages#login'
  get  '/contact',  to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'

  resources :microposts
  resources :cadavers
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'application#hello'

  root 'static_pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cadaver.rb
class Cadaver < ApplicationRecord
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  validates :content, length: { maximum: 10 } , :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts

  validates :name , :presence => true

  validates :surname, :presence => true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }

  before_save {self.email.downcase!}

  has_secure_password

  validates :password, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello"
  end

end

app/controllers/cadavers_controller.rb
class CadaversController < ApplicationController
  before_action :set_cadaver, only: [:show, :edit, :update, :destroy]

  # GET /cadavers
  # GET /cadavers.json
  def index
    @cadavers = Cadaver.all
  end

  # GET /cadavers/1
  # GET /cadavers/1.json
  def show
  end

  # GET /cadavers/new
  def new
    @cadaver = Cadaver.new
  end

  # GET /cadavers/1/edit
  def edit
  end

  # POST /cadavers
  # POST /cadavers.json
  def create
    @cadaver = Cadaver.new(cadaver_params)

    respond_to do |format|
      if @cadaver.save
        format.html { redirect_to @cadaver, notice: 'Cadaver was successfully created.' }
        format.json { render :show, status: :created, location: @cadaver }
      else
        format.html { render :new }
        format.json { render json: @cadaver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadavers/1
  # PATCH/PUT /cadavers/1.json
  def update
    respond_to do |format|
      if @cadaver.update(cadaver_params)
        format.html { redirect_to @cadaver, notice: 'Cadaver was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadaver }
      else
        format.html { render :edit }
        format.json { render json: @cadaver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadavers/1
  # DELETE /cadavers/1.json
  def destroy
    @cadaver.destroy
    respond_to do |format|
      format.html { redirect_to cadavers_url, notice: 'Cadaver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadaver
      @cadaver = Cadaver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadaver_params
      params.require(:cadaver).permit(:name, :surname, :birth, :death)
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def login
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title='')
    base_title="Calife Rails One"
    if title.empty?
      return base_title
    else
      return title+' | '+base_title
    end
  end
end

app/helpers/cadavers_helper.rb
module CadaversHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cadavers/_form.html.erb
<%= form_with(model: cadaver, local: true) do |form| %>
  <% if cadaver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cadaver.errors.count, "error") %> prohibited this cadaver from being saved:</h2>

      <ul>
      <% cadaver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cadaver_name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :cadaver_surname %>
  </div>

  <div class="field">
    <%= form.label :birth %>
    <%= form.date_select :birth, id: :cadaver_birth %>
  </div>

  <div class="field">
    <%= form.label :death %>
    <%= form.date_select :death, id: :cadaver_death %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cadavers/edit.html.erb
<h1>Editing Cadaver</h1>

<%= render 'form', cadaver: @cadaver %>

<%= link_to 'Show', @cadaver %> |
<%= link_to 'Back', cadavers_path %>

app/views/cadavers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cadavers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Birth</th>
      <th>Death</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadavers.each do |cadaver| %>
      <tr>
        <td><%= cadaver.name %></td>
        <td><%= cadaver.surname %></td>
        <td><%= cadaver.birth %></td>
        <td><%= cadaver.death %></td>
        <td><%= link_to 'Show', cadaver %></td>
        <td><%= link_to 'Edit', edit_cadaver_path(cadaver) %></td>
        <td><%= link_to 'Destroy', cadaver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cadaver', new_cadaver_path %>

app/views/cadavers/new.html.erb
<h1>New Cadaver</h1>

<%= render 'form', cadaver: @cadaver %>

<%= link_to 'Back', cadavers_path %>

app/views/cadavers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cadaver.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @cadaver.surname %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @cadaver.birth %>
</p>

<p>
  <strong>Death:</strong>
  <%= @cadaver.death %>
</p>

<%= link_to 'Edit', edit_cadaver_path(@cadaver) %> |
<%= link_to 'Back', cadavers_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Calife Rails One", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "About",  about_path %></li>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_header_default.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!-- Bootstrap -->
<link href="css/bootstrap.min.css" rel="stylesheet">

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <%= render 'layouts/rails_header_default' %>

  <%= render 'layouts/shim' %>

</head>

<body>

<%= render 'layouts/header' %>

<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

</body>

</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :micropost_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :micropost_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">

  <h1>HOME</h1>
  <p>Supporto Tecnico Revenge</p>

  <h2>
    This is the home page for the<%= link_to "Ruby on Rails Tutorial",   'http://www.railstutorial.org/' %>sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>

</div>

<%= link_to image_tag("virtualMachine.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/static_pages/login.html.erb
<h1>StaticPages#login</h1>
<p>Find me in app/views/static_pages/login.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
  <%= form.label :surname %>
  <%= form.text_field :surname, id: :user_surname %>
</div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>First post content:</strong>
  <%=
    if @user.microposts.length!=0
        @user.microposts.first.content
      else
       "No post published"
    end


  %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>